### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jothoma1** [zionio/graylog-grok-rundeck-jobs-log#1]
Hi,
Thanks for your pattern, just a question about forwarding rundeck logs to graylog.
How do you do it ?
Thanks in advance !

**Comment by zionio** [comment]
Hi,
 you can use [Graylog Collector-Sidecar](http://docs.graylog.org/en/2.4/pages/collector_sidecar.html) to send Rundeck jobs log (`/var/log/rundeck/rundeck.jobs.log`) to GL with [Filebeat](http://docs.graylog.org/en/2.4/pages/collector_sidecar.html#beats-backend) backend.
